export const NatureOfBusiness = [
    { label: "Accelerators", value: "Accelerators" },
    { label: "Adhesives & Paints", value: "Adhesives & Paints" },
    { label: "Aerospace", value: "Aerospace" },
    { label: "Agriculture", value: "Agriculture" },
    { label: "Agriculture and Agribusiness", value: "Agriculture and Agribusiness" },
    { label: "Architecture & Design", value: "Architecture & Design" },
    { label: "Artificial Intelligence", value: "Artificial Intelligence" },
    { label: "Arts and Culture", value: "Arts and Culture" },
    { label: "Associations and Federations", value: "Associations and Federations" },
    { label: "Automotive", value: "Automotive" },
    { label: "Automotive Glass", value: "Automotive Glass" },
    { label: "Aviation", value: "Aviation" },
    { label: "Banks and Other Financial Institutions", value: "Banks and Other Financial Institutions" },
    { label: "Beveled Glass", value: "Beveled Glass" },
    { label: "Building Materials", value: "Building Materials" },
    { label: "Business Council", value: "Business Council" },
    { label: "Chambers of Commerce and Industry", value: "Chambers of Commerce and Industry" },
    { label: "Chemical Industry", value: "Chemical Industry" },
    { label: "Coloured and Pure Glass", value: "Coloured and Pure Glass" },
    { label: "Commerce", value: "Commerce" },
    { label: "Conglomerate", value: "Conglomerate" },
    { label: "Construction and Engineering", value: "Construction and Engineering" },
    { label: "Consultancy", value: "Consultancy" },
    { label: "Consumer Goods", value: "Consumer Goods" },
    { label: "Contracting", value: "Contracting" },
    { label: "Corporate", value: "Corporate" },
    { label: "Cosmetics", value: "Cosmetics" },
    { label: "Decor Glass", value: "Decor Glass" },
    { label: "Defense/Military", value: "Defense/Military" },
    { label: "Digital Solution", value: "Digital Solution" },
    { label: "Diplomatic Mission", value: "Diplomatic Mission" },
    { label: "Dust Control & Vacuum Cleaners", value: "Dust Control & Vacuum Cleaners" },
    { label: "Economic Development", value: "Economic Development" },
    { label: "Education", value: "Education" },
    { label: "Energy and Mining", value: "Energy and Mining" },
    { label: "Event Organizer", value: "Event Organizer" },
    { label: "Facades and Cabins ", value: "Facades and Cabins " },
    { label: "Facilities Management", value: "Facilities Management" },
    { label: "Fiber Glass", value: "Fiber Glass" },
    { label: "Fishery", value: "Fishery" },
    { label: "Flat Glass", value: "Flat Glass" },
    { label: "Flooring", value: "Flooring" },
    { label: "Food & Beverages", value: "Food & Beverages" },
    { label: "Foreign Affairs", value: "Foreign Affairs" },
    { label: "Furniture Manufacturers", value: "Furniture Manufacturers" },
    { label: "Glass Machinery", value: "Glass Machinery" },
    { label: "Glass Manufacturing", value: "Glass Manufacturing" },
    { label: "Government", value: "Government" },
    { label: "Government Department", value: "Government Department" },
    { label: "Government Programs and Initiatives", value: "Government Programs and Initiatives" },
    { label: "Green Technology and Climate Change", value: "Green Technology and Climate Change" },
    { label: "Hand Craft", value: "Hand Craft" },
    { label: "Handrail", value: "Handrail" },
    { label: "Healthcare and Pharmaceutical", value: "Healthcare and Pharmaceutical" },
    { label: "Heat Treated Glass", value: "Heat Treated Glass" },
    { label: "Hospitality", value: "Hospitality" },
    { label: "Immigration Service", value: "Immigration Service" },
    { label: "Incubators", value: "Incubators" },
    { label: "Infrastructure", value: "Infrastructure" },
    { label: "Insurance", value: "Insurance" },
    { label: "Inter-governmental organizations (IGOs)", value: "Inter-governmental organizations (IGOs)" },
    { label: "Investment & Trade", value: "Investment & Trade" },
    { label: "Investment and Freezones", value: "Investment and Freezones" },
    { label: "Investment Firm", value: "Investment Firm" },
    { label: "Investment Promotion Agency", value: "Investment Promotion Agency" },
    { label: "Investor", value: "Investor" },
    { label: "IT/ ICT and Telecommunication", value: "IT/ ICT and Telecommunication" },
    { label: "Law and Legal Affairs", value: "Law and Legal Affairs" },
    { label: "Life Sciences", value: "Life Sciences" },
    { label: "Lightning", value: "Lightning" },
    { label: "Local Government Units", value: "Local Government Units" },
    { label: "Logistics and Transportation", value: "Logistics and Transportation" },
    { label: "Luxury Goods & Jewelry", value: "Luxury Goods & Jewelry" },
    { label: "Management & Investment", value: "Management & Investment" },
    { label: "Manufacturing", value: "Manufacturing" },
    { label: "Maritime", value: "Maritime" },
    { label: "Marketing", value: "Marketing" },
    { label: "Marketing and Advertising", value: "Marketing and Advertising" },
    { label: "MDF/ Panels and Laminates", value: "MDF/ Panels and Laminates" },
    { label: "Media", value: "Media" },
    { label: "Ministries", value: "Ministries" },
    { label: "Non-Profit Organizations", value: "Non-Profit Organizations" },
    { label: "Oil and Gas", value: "Oil and Gas" },
    { label: "Others", value: "Others" },
    { label: "Paper Industry", value: "Paper Industry" },
    { label: "Partitions Skylights", value: "Partitions Skylights" },
    { label: "Pharmaceutical Glass", value: "Pharmaceutical Glass" },
    { label: "Plastics", value: "Plastics" },
    { label: "Plywood/ Hardboard Decorative", value: "Plywood/ Hardboard Decorative" },
    { label: "Private Equity", value: "Private Equity" },
    { label: "Private Sector", value: "Private Sector" },
    { label: "Professional Services", value: "Professional Services" },
    { label: "Property Development", value: "Property Development" },
    { label: "Property Portal", value: "Property Portal" },
    { label: "Property Valuation", value: "Property Valuation" },
    { label: "Protective Glass", value: "Protective Glass" },
    { label: "Publishing House", value: "Publishing House" },
    { label: "Pyrex Glass", value: "Pyrex Glass" },
    { label: "Raw Materials", value: "Raw Materials" },
    { label: "Real Estate", value: "Real Estate" },
    { label: "Real Estate Brokers", value: "Real Estate Brokers" },
    { label: "Regional Organizations", value: "Regional Organizations" },
    { label: "Retail", value: "Retail" },
    { label: "Robotics", value: "Robotics" },
    { label: "Security", value: "Security" },
    { label: "Shipbuilding", value: "Shipbuilding" },
    { label: "Shock Resistant Glass", value: "Shock Resistant Glass" },
    { label: "Smart Solutions", value: "Smart Solutions" },
    { label: "Software", value: "Software" },
    { label: "Sovereign Wealth Funds", value: "Sovereign Wealth Funds" },
    { label: "Special Economic Zones", value: "Special Economic Zones" },
    { label: "Spider Glass", value: "Spider Glass" },
    { label: "Sports and Recreation", value: "Sports and Recreation" },
    { label: "Startups", value: "Startups" },
    { label: "Supermarket", value: "Supermarket" },
    { label: "Supplier", value: "Supplier" },
    { label: "Table Wear", value: "Table Wear" },
    { label: "Technology", value: "Technology" },
    { label: "Textile and Apparel", value: "Textile and Apparel" },
    { label: "Timber/ Hardwood & Softwood", value: "Timber/ Hardwood & Softwood" },
    { label: "Tools & Cutting Machines", value: "Tools & Cutting Machines" },
    { label: "Tourism and Hospitality", value: "Tourism and Hospitality" },
    { label: "Trade & Industry", value: "Trade & Industry" },
    { label: "Transportation", value: "Transportation" },
    { label: "Treatment Products and Composite", value: "Treatment Products and Composite" },
    { label: "UN Specialized Agency", value: "UN Specialized Agency" },
    { label: "Universities & Academic Institutions", value: "Universities & Academic Institutions" },
    { label: "Utilities", value: "Utilities" },
    { label: "Veneer", value: "Veneer" },
    { label: "Venture Capital", value: "Venture Capital" },
    { label: "Venture Capital - PropTech", value: "Venture Capital - PropTech" },
    { label: "Water Recycle", value: "Water Recycle" },
    { label: "Wood", value: "Wood" },
    { label: "Wood Accessories (Doors-Windows-Fittings)", value: "Wood Accessories (Doors-Windows-Fittings)" },
    { label: "Wood Furniture Manufacturers", value: "Wood Furniture Manufacturers" },
    { label: "Wood Suppliers", value: "Wood Suppliers" },
    { label: "Wood Working Machinery", value: "Wood Working Machinery" },
    { label: "Wooden Windows and Doors", value: "Wooden Windows and Doors" },

]